# -*- coding: utf-8 -*-
"""Titanic Survivors_Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11lX-5CV4fBX5b4xFrA4TZdg1DaDeL7AG

# Titanic_Survivors_Project
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.DataFrame(pd.read_csv("/content/train (1) (1).csv"))
data.head()

data

data.isnull()
data.isnull().sum()

"""# Droping columns which have more than 35% of data missing"""

drop_col = data.isnull().sum()[data.isnull().sum()>35/100 * data.shape[0]]
drop_col
# only column cabin satisfies this condition

"""#  1. **We** can conclude here that Cabin column does not have much significance in deciding the survival rate so we have dropped it"""

data = data.drop(["Cabin"], axis =1)

data.isnull().sum()
# need to fill the missing values

data.fillna(data.mean(), inplace = True)
data.isnull().sum()
# filled the missing values in age column with age

data["Embarked"]
data["Embarked"].describe()

# filling missing values with S as its the most frequent occuring value
data["Embarked"].fillna("S", inplace = True)

data.isnull().sum()
# all missing values filled

# now establing relations to draw conclusions
data.corr()

"""# 2. We can see Pclass and Fare have a good correlation (magnitude) i.e when Pclass decreases the Fare increases."""

data["Family_size"] = data["SibSp"]+data["Parch"]
data = data.drop(["Parch", "SibSp"], axis =1)
data.corr()

"""# 3. There is a good correlation between Pclass and survival rate (approx 33%) So, we can say that passengers from lower classes (rich people)survived more.
 
"""

data.plot(x='Survived', y='Age', style='o')
plt.show()

data["Alone"] = [0 if data["Family_size"][i]>0 else 1 for i in data.index]
data["Alone"]

data.corr()

data.groupby(["Alone"])["Survived"].mean()

"""# 4. Here we can conclude that if a person had a family he/she had a better survival rate means people with families were prioritized.

# 5. Through the correlation between fare and alone we can say that the person who was alone he/she had a higher ticket fare(since the relation is negative)
"""

data.groupby(["Sex"])["Survived"].mean()

"""# 6. It is very evident from above output that female passengers had a better rate of survival than male passengers.

"""

data.groupby(["Embarked"])["Survived"].mean()

"""# 7. Now here we can say that the survival rate was highest for passengers with embarkation as C

# CONCLUSIONS


* #  There is a good correlation between Pclass and survival rate (approx 33%) So, we can say that passengers from lower classes (rich people)survived more.
 
* # It is very evident from above output that female passengers had a better rate of survival than male passengers.

* # We can conclude that if a person had a family he/she had a better survival rate means people with families were prioritized.
*  # We can say that the survival rate was highest for passengers with embarkation as C.
*  # We can conclude here that Cabin column does not have much significance in deciding the survival rate  
*   # Pclass and Fare have a good correlation (magnitude) i.e when Pclass decreases the Fare increases.
"""